"rapperData":[
	{
		"name":"Jay-Z",
		"type":"legacy",
		"moves":[
			{
				"name":"Hard Knock Life",
				"lyrics":[
					"I don't know how to sleep, I gotta eat, stay on my toes\nGot a lotta beef, so logically, I prey on my foes\nHustlin' is still inside of me, and as far as progress\nYou'd be hard-pressed to find another rapper hot as me",
					"I'm tight grill with the phony – Rappers, y'all might feel we homies. I'm like, \"Still, y'all don't know me.\" Shit, I'm tight grill when my situation ain't improvin' – I'm tryna murder everything movin' – feel me?",
					"I flow for chicks wishin', they ain't have to strip to pay tuition. I see your vision, mama! I put my money on the longshots. All my ballers that's born to clock. Know I'ma be on top whether I perform or not",
					"I gave you prophecy on my first joint, and y'all lamed out. Didn't really appreciate it 'til the second one came out. So I stretched the game out, etched your name out, put Jigga on top and dropped albums non-stop for ya, nigga!"
				]
			},
			{
				"name":"Dead Presidents II",
				"lyrics":[
					"Ahh, who wanna bet us that we don't touch lettuce? Stack cheddars forever, live treacherous, all the et ceteras. To the death of us, me and my confidants, we shine, you feel the ambiance? Y'all niggas just rhyme.",
					"The Soviet, the Unified steady flow - You already know: you light, I'm heavy, roll heavy dough. Mic-macheted your flow. Your paper falls slow like confetti, mine's a steady grow, perico",
					"I'll make, you and your wack mans fold like bad hands. Roll like Monopoly, advance. You're coppin' me like - white crystal. I gross the most at the end of the fiscal year than these niggas can wish to",
					"Crime family, well-connected, Jay-Z. And you, fake thugs is unplugged like MTV. I empty three, take your treasure, my pleasure. Dead presidentials, politics as usual—BLAOW!"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song4",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Nas",
		"type":"legacy",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song4",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Snoop Dogg",
		"type":"legacy",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Lil Wayne",
		"type":"legacy",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Andre 3000",
		"type":"legacy",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song4",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Drake",
		"type":"elite",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"J. Cole",
		"type":"elite",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song4",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Kendrick Lamar",
		"type":"elite",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song4",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Wale",
		"type":"elite",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Nicki Minaj",
		"type":"elite",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Jeezy",
		"type":"finesse",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Future",
		"type":"finesse",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}

		]
	},
	{
		"name":"21 Savage",
		"type":"finesse",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Lil Durk",
		"type":"finesse",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}

		]
	},
	{
		"name":"Lil Baby",
		"type":"finesse",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Isaiah Rashad",
		"type":"raw",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Pusha-T",
		"type":"raw",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Rapsody",
		"type":"raw",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Big K.R.I.T.",
		"type":"raw",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	},
	{
		"name":"Freddie Gibbs",
		"type":"raw",
		"moves":[
			{
				"name":"Song1",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song2",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			},
			{
				"name":"Song3",
				"lyrics":[
					"lyrics1",
					"lyrics2",
					"lyrics3",
					"lyrics4"
				]
			}
		]
	}
]
